WIP: Add validate number without region code
flutter-form-builder-ecosystem/phone_number pull request #73
Opened 2022-08-02 16:11 UTC by deandreamatias

## Connection with issue(s)

Close #64 

## Solution description

If don't pass region code to validator, try validate a complete number

## To Do

- [ ] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [ ] Check the original issue to confirm it is fully satisfied
- [ ] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [ ] If apply, add documentation to code properties and package readme

2022-08-02 19:40 UTC, ooglek commented
That looks great! If I do not pass a region code, still validate if the number is valid!

Thank you for digging into this. I can try to test it as well.

2022-08-03 13:03 UTC, iamsahilsonawane requested changes

2022-08-03 13:03 UTC, iamsahilsonawane commented on README.md
>  PhoneNumberUtil plugin = PhoneNumberUtil();
Will need to update (region as named param) the below examples

For e.g.: 
```diff
- bool isValid = await plugin.validate(springFieldUSASimpleNoRegion, region.code);
+ bool isValid = await plugin.validate(springFieldUSASimpleNoRegion, region: region.code);
```

2022-08-03 13:05 UTC, iamsahilsonawane commented
I understand that it's a WIP, still have added these comments as reference

2022-08-03 20:42 UTC, deandreamatias commented
I tested in Android with random numbers and works fine

2022-08-04 13:58 UTC, iamsahilsonawane approved these changes
LGTM!

2022-08-04 14:05 UTC, merged

2022-08-07 20:11 UTC, ooglek commented
When will this get pushed in a version bump? Thanks for fixing!

2022-08-07 20:54 UTC, deandreamatias commented
When finish the readme refactor

2022-08-08 21:13 UTC, ooglek commented
This breaks `format()` on IOS

https://github.com/flutter-form-builder-ecosystem/phone_number/blob/688e85155106a505385cab7c010fe750c64d6d7b/ios/Classes/SwiftPhoneNumberPlugin.swift#L26-L42

Passing `string` as `+5518988012364` and `region` as `US` and getting the error
PlatformException(InvalidArgument, The 'string' argument is missing., null, null)

2022-08-08 21:35 UTC, ooglek commented
@deandreamatias Looks like the IOS Swift Code needs modification as well.

2022-08-08 21:54 UTC, deandreamatias commented
Open a issue please

2022-08-09 02:24 UTC, ooglek commented
Done, Issue #82